package modelo;

public class ProvinciasArgentinas {
	
	private static final String[][] provinciasYVecinos = {
			{"Buenos Aires","Entre Ríos"},
			{"Buenos Aires","Santa Fe"},
			{"Buenos Aires","La Pampa"},
			{"Buenos Aires","Río Negro"},
			{"Catamarca","Salta"},
			{"Catamarca","Tucumán"},
			{"Catamarca","La Rioja"},
			{"Catamarca","Córdoba"},
			{"Chaco","Salta"},
			{"Chaco","Formosa"},
			{"Chaco","Santiago del Estero"},
			{"Chaco","Santa Fe"},
			{"Chaco","Corrientes"},
			{"Chubut","Río Negro"},
			{"Chubut","Santa Cruz"},
			{"Córdoba","Santiago del Estero"},
			{"Córdoba","Catamarca"},
			{"Córdoba","La Rioja"},
			{"Córdoba","San Luis"},
			{"Córdoba","Santa Fe"},
			{"Córdoba","Buenos Aires"},
			{"Córdoba","La Pampa"},
			{"Corrientes","Misiones"},
			{"Corrientes","Chaco"},
			{"Corrientes","Santa Fe"},
			{"Corrientes","Entre Ríos"},
			{"Entre Ríos","Corrientes"},
			{"Entre Ríos","Santa Fe"},
			{"Entre Ríos","Buenos Aires"},
			{"Formosa","Salta"},
			{"Formosa","Chaco"},
			{"Jujuy", "Salta" },
			{"La Pampa","Córdoba"},
			{"La Pampa","San Luis"},
			{"La Pampa","Mendoza"},
			{"La Pampa","Neuquén"},
			{"La Pampa","Buenos Aires"},
			{"La Pampa","Río Negro"},
			{"La Rioja","Catamarca"},
			{"La Rioja","San Juan"},
			{"La Rioja","Córdoba"},
			{"La Rioja","San Luis"},
			{"Mendoza","San Juan"},
			{"Mendoza","San Luis"},
			{"Mendoza","La Pampa"},
			{"Mendoza","Neuquén"},
			{"Misiones","Corrientes"},
			{"Neuquén","Mendoza"},
			{"Neuquén","Río Negro"},
			{"Río Negro","La Pampa"},
			{"Río Negro","Neuquén"},
			{"Río Negro","Buenos Aires"},
			{"Río Negro","Chubut"},
			{"Salta","Jujuy"},
			{"Salta","Catamarca"},
			{"Salta","Tucumán"},
			{"Salta","Santiago del Estero"},
			{"Salta","Chaco"},
			{"Salta","Formosa"},
			{"San Juan","La Rioja"},
			{"San Juan","San Luis"},
			{"San Juan","Mendoza"},
			{"San Luis","La Rioja"},
			{"San Luis","San Juan"},
			{"San Luis","Mendoza"},
			{"San Luis","Córdoba"},
			{"San Luis","La Pampa"},
			{"Santa Cruz","Chubut"},
			{"Santa Cruz","Tierra del Fuego"},
			{"Santa Fe","Chaco"},
			{"Santa Fe","Santiago del Estero"},
			{"Santa Fe","Córdoba"},
			{"Santa Fe","Corrientes"},
			{"Santa Fe","Entre Ríos"},
			{"Santa Fe","Buenos Aires"},
			{"Santiago del Estero","Salta"},
			{"Santiago del Estero","Tucumán"},
			{"Santiago del Estero","Catamarca"},
			{"Santiago del Estero","Chaco"},
			{"Santiago del Estero","Santa Fe"},
			{"Santiago del Estero","Córdoba"},
			{"Tierra del Fuego","Santa Cruz"},
			{"Tucumán","Salta"},
			{"Tucumán","Catamarca"},
			{"Tucumán","Santiago del Estero"}
		
	};

}
